# follows the minimal vagrant install guide for boxes
# see
#    http://docs.vagrantup.com/v2/boxes/base.html
#
# in the inventory file, login using vagrant

- hosts: all
  vars:
    vagrant_pass: $2b$10$8pmWYSM4C1FwImi6.C44MugdKrlFVt5sP2UCN6nq/BnUH.Qcv3CFG # vagrant
    root_pass: $2b$10$8pmWYSM4C1FwImi6.C44MugdKrlFVt5sP2UCN6nq/BnUH.Qcv3CFG # vagrant
  become: yes
  become_user: root
  become_method: su

  # handling default passwords
  tasks:
  - name: Set vagrant user default password
    user: name=vagrant comment="Vagrant user" password={{vagrant_pass}}

  - name: Set root user default password
    user: name=root password={{vagrant_pass}}

  # sshd and sudo config
  # vagrant is allowed to do sudo with no password
  - name: set no use DNS in sshd
    lineinfile: dest=/etc/ssh/sshd_config state=present line="UseDNS no"
  - name: set sudoer on vagrant user
    lineinfile: "dest=/etc/sudoers state=present line='vagrant ALL=(ALL) NOPASSWD: SETENV: ALL'"

  - name: Copy insecure public key
    copy: src=vagrant.pub dest=/home/vagrant/.ssh/authorized_keys owner=vagrant group=vagrant mode=0700



#  tasks:
#  - name: ensure apache is at the latest version
#    yum: pkg=httpd state=latest
#  - name: write the apache config file
#    template: src=/srv/httpd.j2 dest=/etc/httpd.conf
#    notify:
#    - restart apache
#  - name: ensure apache is running (and enable it at boot)
#    service: name=httpd state=started enabled=yes
#  handlers:
#    - name: restart apache
#      service: name=httpd state=restarted
